/*
# NoticiasPro — Seed Sample Articles

## Overview
Inserts 25 sample articles into the `articles` table, matching the mock data
used in the frontend. Each article references a category (by slug) and an
author (by name) via subqueries.

## Notes
- Uses a CTE to insert articles with category_id and author_id resolved from
  category slugs and author names.
- Idempotent: ON CONFLICT (slug) DO NOTHING.
- published_at values are cast to timestamptz explicitly.
*/

WITH article_data AS (
  SELECT
    slug, title, subtitle, summary, content, excerpt, meta_description,
    image, image_alt, category_slug, subcategory_slug, tags,
    author_name, published_at::timestamptz AS published_at, reading_time, views, comments_count, shares,
    is_breaking, is_featured, is_trending, source_name, source_url,
    ai_rewritten, original_language
  FROM (VALUES
    ('real-madrid-firma-goleada-champions-final',
     'El Real Madrid firma una goleada histórica en la final de la Champions League',
     'El equipo blanco se proclama campeón de Europa por decimoquinta vez con un partido memorable',
     'El Real Madrid ha conquistado la Champions League con una victoria aplastante que demuestra el dominio del equipo blanco en Europa.',
     '<p>El Real Madrid ha vuelto a hacer historia en la Champions League con una victoria aplastante que confirma su dominio en el fútbol europeo. El equipo blanco, dirigido por Carlo Ancelotti, demostró una vez más por qué es el rey de Europa.</p><h2>Un partido para la historia</h2><p>Desde el primer minuto, el Real Madrid mostró su intención de dominar el partido. La posesión del balón y la presión alta fueron clave para desactivar al rival, que nunca encontró su ritmo en el encuentro.</p><p>Los goles llegaron en ráfaga, demostrando la pegada del equipo. Vinicius Jr. fue el protagonista indiscutible con dos goles y una asistencia, mientras que Bellingham completó una actuación magistral en el mediocampo.</p><h2>Ancelotti: "Este equipo es único"</h2><p>El técnico italiano destacó la actitud del equipo: "Estoy muy orgulloso de estos jugadores. Han demostrado un nivel de compromiso y calidad que hace que este equipo sea único en la historia del fútbol".</p><p>El capitán del Real Madrid, Nacho, recogió el trofeo entre los aplausos de los aficionados que llenaban el estadio. La celebración se prolongó durante horas en el césped y en los vestuarios.</p><h2>Una temporada de récord</h2><p>Esta Champions League corona una temporada de récord para el Real Madrid, que ha logrado el doblete con la Liga y la máxima competición continental. El equipo ha batido numerosos registros a lo largo de la campaña.</p><p>La directiva ya trabaja en la planificación de la próxima temporada, con el objetivo de seguir reforzando un plantel que ha demostrado ser el mejor de Europa. El mercado de fichajes promete ser movido en el Santiago Bernabéu.</p>',
     'El equipo blanco se proclama campeón de Europa por decimoquinta vez con un partido memorable ante su eterno rival.',
     'El Real Madrid gana la Champions League con una goleada histórica. Vinicius y Bellingham protagonistas. Lee el análisis completo del partido.',
     'https://images.pexels.com/photos/46798/pexels-photo-46798.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Jugadores del Real Madrid celebrando la victoria en la final de la Champions League',
     'real-madrid', 'champions-league', ARRAY['Real Madrid','Champions League','Carlo Ancelotti','Vinicius Jr','Bellingham','Fútbol'],
     'Carlos Martínez', '2026-07-04T18:30:00Z', 4, 245680, 1247, 8920, true, true, true,
     'Marca', 'https://example.com/source1', true, 'es'),
    ('barcelona-presenta-nuevo-fichaje-estrella',
     'El FC Barcelona presenta su nuevo fichaje estrella para la próxima temporada',
     'El club culé ha cerrado el fichaje por 80 millones de euros tras semanas de negociación',
     'El FC Barcelona ha hecho oficial la incorporación de un nuevo jugador estrella que refuerza el proyecto deportivo.',
     '<p>El FC Barcelona ha hecho oficial la presentación de su nuevo fichaje estrella para la próxima temporada en un evento multitudinario en el Camp Nou.</p><h2>Un fichaje de garantías</h2><p>El jugador llega procedente de la liga italiana por una cantidad cercana a los 80 millones de euros, convirtiéndose en uno de los fichajes más caros de la historia del club culé.</p><p>El director deportivo del Barcelona destacó la calidad del jugador y su importancia para el proyecto: "Es un jugador que encaja perfectamente en nuestro estilo de juego y que nos va a dar muchas alegrías".</p><h2>El proyecto de Xavi</h2><p>Este fichaje refuerza el proyecto deportivo liderado por Xavi Hernández, que busca devolver al Barcelona a la cima del fútbol europeo tras una temporada complicada.</p><p>El técnico barcelonista ya ha diseñado el nuevo sistema táctico que aprovechará al máximo las cualidades del nuevo jugador, que se integrará inmediatamente en la dinámica del equipo.</p>',
     'El club culé ha cerrado el fichaje por 80 millones de euros tras semanas de negociación con el club italiano.',
     'El FC Barcelona presenta su nuevo fichaje estrella por 80 millones. Análisis del fichaje y su impacto en el proyecto de Xavi.',
     'https://images.pexels.com/photos/274506/pexels-photo-274506.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Nuevo fichaje del FC Barcelona posando con la camiseta del club en el Camp Nou',
     'barcelona', 'mercado-fichajes', ARRAY['FC Barcelona','Fichajes','LaLiga','Xavi','Mercado de fichajes'],
     'Carlos Martínez', '2026-07-04T16:00:00Z', 3, 187340, 856, 4520, false, true, true,
     'Mundo Deportivo', 'https://example.com/source2', true, 'es'),
    ('atletico-madrid-renueva-contrato-entrenador',
     'El Atlético de Madrid renueva el contrato de su entrenador hasta 2028',
     'El club del Metropolitano confía en el proyecto del técnico para los próximos años',
     'El Atlético de Madrid ha anunciado la renovación de contrato de su entrenador hasta 2028.',
     '<p>El Atlético de Madrid ha hecho oficial la renovación de contrato de su entrenador hasta 2028, en una muestra de confianza hacia el proyecto deportivo del técnico.</p><h2>Un proyecto a largo plazo</h2><p>El club colchonero ha querido asegurar la continuidad del entrenador que ha transformado el estilo de juego del equipo en los últimos años.</p><p>La renovación incluye una cláusula de rescisión importante y un proyecto deportivo ambicioso que busca devolver al Atlético a lo más alto del fútbol español y europeo.</p>',
     'El club del Metropolitano confía en el proyecto del técnico para los próximos años tras una temporada exitosa.',
     'El Atlético de Madrid renueva a su entrenador hasta 2028. Detalles del contrato y el proyecto deportivo del club colchonero.',
     'https://images.pexels.com/photos/47730/pexels-photo-47730.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Entrenador del Atlético de Madrid celebrando en el banquillo del Metropolitano',
     'atletico-madrid', NULL, ARRAY['Atlético de Madrid','LaLiga','Renovación','Diego Simeone'],
     'Carlos Martínez', '2026-07-04T14:30:00Z', 2, 98230, 423, 1840, false, false, false,
     'AS', 'https://example.com/source3', true, 'es'),
    ('seleccion-espanola-clasifica-eurocopa-final',
     'La Selección Española se clasifica para la final de la Eurocopa',
     'La Roja logra una victoria épica en la prórroga y jugará la final del torneo continental',
     'La Selección Española de fútbol ha logrado clasificarse para la final de la Eurocopa tras una victoria épica.',
     '<p>La Selección Española ha logrado una clasificación épica para la final de la Eurocopa tras vencer en la prórroga con un gol decisivo en los últimos minutos.</p><h2>Un partido emocionante</h2><p>El partido fue un auténtico espectáculo de ida y vuelta, con dos equipos que ofrecieron un fútbol de altísimo nivel. España demostró su mejor versión y supo sufrir cuando fue necesario.</p><p>Los jóvenes talentos del equipo fueron los protagonistas, con una actuación estelar de los mediocampistas que controlaron el tempo del encuentro.</p>',
     'La Roja logra una victoria épica en la prórroga y jugará la final del torneo continental.',
     'La Selección Española se clasifica para la final de la Eurocopa con una victoria épica. Análisis del partido y la final.',
     'https://images.pexels.com/photos/390853/pexels-photo-390853.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Jugadores de la Selección Española celebrando el gol de la clasificación',
     'seleccion-espanola', NULL, ARRAY['Selección Española','Eurocopa','La Roja','Fútbol'],
     'Carlos Martínez', '2026-07-04T12:00:00Z', 3, 156780, 678, 3210, true, false, true,
     'Marca', 'https://example.com/source4', true, 'es'),
    ('laliga-clasificacion-actualizada-jornada',
     'LaLiga: clasificación actualizada tras la última jornada',
     'Analizamos la situación de los equipos de LaLiga EA Sports tras los últimos resultados',
     'Repaso completo a la clasificación de LaLiga tras la última jornada con el análisis de cada equipo.',
     '<p>La jornada de LaLiga EA Sports ha dejado importantes movimientos en la clasificación, con varios equipos que han cambiado de posición tras los últimos resultados.</p><h2>Cabeza de la clasificación</h2><p>Los equipos de cabeza mantienen la lucha por el título con diferencias mínimas. La competición se ha vuelto muy igualada y cualquier error puede ser decisivo.</p><h2>Zona de descenso</h2><p>En la zona baja, la lucha por la permanencia está más viva que nunca con varios equipos que se juegan la salvación en las últimas jornadas.</p>',
     'Analizamos la situación de los equipos de LaLiga EA Sports tras los últimos resultados de la jornada.',
     'Clasificación de LaLiga EA Sports actualizada tras la última jornada. Análisis de la lucha por el título y el descenso.',
     'https://images.pexels.com/photos/47756/pexels-photo-47756.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Estadio de fútbol durante un partido de LaLiga con los jugadores en el césped',
     'laliga', NULL, ARRAY['LaLiga','Clasificación','Fútbol','EA Sports'],
     'Carlos Martínez', '2026-07-04T10:00:00Z', 5, 89450, 234, 1230, false, false, false,
     'AS', 'https://example.com/source5', true, 'es'),
    ('premier-league-fichaje-estrella-verano',
     'Premier League: el fichaje estrella del verano se confirma',
     'Uno de los grandes clubes de la Premier League ha cerrado el fichaje más caro de la temporada',
     'La Premier League registra el fichaje más caro del verano con un traspaso millonario.',
     '<p>La Premier League ha registrado el fichaje más caro del verano con un traspaso que supera los 100 millones de euros.</p><h2>Un movimiento histórico</h2><p>El club inglés ha hecho un esfuerzo económico importante para incorporar al jugador que era uno de los objetivos prioritarios del mercado.</p><p>El jugador llega procedente de una liga europea y se compromete con el club inglés por las próximas cinco temporadas.</p>',
     'Uno de los grandes clubes de la Premier League ha cerrado el fichaje más caro de la temporada.',
     'Premier League: fichaje estrella del verano confirmado por más de 100 millones. Detalles del traspaso y análisis.',
     'https://images.pexels.com/photos/274506/pexels-photo-274506.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Estadio de la Premier League lleno durante un partido',
     'premier-league', NULL, ARRAY['Premier League','Fichajes','Fútbol','Inglaterra'],
     'Carlos Martínez', '2026-07-04T09:00:00Z', 3, 72340, 312, 980, false, false, true,
     'BBC Sport', 'https://example.com/source6', true, 'en'),
    ('openai-lanza-nuevo-modelo-gpt-revolucionario',
     'OpenAI lanza un nuevo modelo de IA que revoluciona el sector tecnológico',
     'La nueva versión promete capacidades sin precedentes en razonamiento y comprensión del lenguaje',
     'OpenAI ha presentado un nuevo modelo de inteligencia artificial que promete revolucionar el sector.',
     '<p>OpenAI ha presentado oficialmente su nuevo modelo de inteligencia artificial, que promete capacidades sin precedentes en razonamiento, comprensión del lenguaje y generación de contenido.</p><h2>Capacidades mejoradas</h2><p>El nuevo modelo ofrece mejoras significativas en comparación con su predecesor, con una capacidad de razonamiento que se acerca a la humana en muchas tareas complejas.</p><p>Los benchmarks iniciales muestran mejoras del 30% en razonamiento lógico y del 45% en comprensión de contexto, lo que sitúa a este modelo por delante de la competencia.</p><h2>Implicaciones para la industria</h2><p>Este lanzamiento tiene importantes implicaciones para la industria de la IA, con un impacto que se extiende desde la atención al cliente hasta la creación de contenido y la programación.</p><p>Los expertos del sector ya analizan las posibles aplicaciones de este nuevo modelo en diferentes campos, desde la medicina hasta la educación.</p>',
     'La nueva versión promete capacidades sin precedentes en razonamiento y comprensión del lenguaje natural.',
     'OpenAI lanza un nuevo modelo de IA revolucionario con capacidades mejoradas de razonamiento. Análisis del impacto en el sector tecnológico.',
     'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Representación visual de inteligencia artificial con circuitos y luces',
     'ia', NULL, ARRAY['OpenAI','Inteligencia Artificial','GPT','Tecnología','IA'],
     'Laura Sánchez', '2026-07-04T15:00:00Z', 4, 134560, 567, 4320, false, true, true,
     'The Verge', 'https://example.com/source7', true, 'en'),
    ('apple-presenta-nuevo-iphone-con-inteligencia-artificial',
     'Apple presenta el nuevo iPhone con funciones de inteligencia artificial integradas',
     'La compañía de Cupertino revoluciona su smartphone con capacidades de IA en el dispositivo',
     'Apple ha presentado el nuevo iPhone con funciones avanzadas de inteligencia artificial integradas.',
     '<p>Apple ha presentado oficialmente el nuevo iPhone con funciones de inteligencia artificial integradas directamente en el dispositivo, marcando un antes y un después en la evolución del smartphone.</p><h2>Apple Intelligence</h2><p>La nueva función, denominada Apple Intelligence, permite realizar tareas avanzadas de IA directamente en el dispositivo sin necesidad de conexión a internet, garantizando la privacidad del usuario.</p><p>Las capacidades incluyen generación de texto, resumen de notificaciones, edición avanzada de fotos y un Siri completamente renovado con capacidades de razonamiento.</p><h2>Características técnicas</h2><p>El nuevo iPhone incorpora un procesador más potente específicamente diseñado para las tareas de IA, con un motor neuronal mejorado que multiplica el rendimiento.</p>',
     'La compañía de Cupertino revoluciona su smartphone con capacidades de IA en el dispositivo.',
     'Apple presenta el nuevo iPhone con Apple Intelligence. Funciones de IA integradas, características técnicas y análisis completo.',
     'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Nuevo iPhone de Apple con funciones de inteligencia artificial',
     'apple', NULL, ARRAY['Apple','iPhone','Inteligencia Artificial','Tecnología','Smartphone'],
     'Laura Sánchez', '2026-07-04T13:00:00Z', 4, 112340, 445, 2890, false, false, true,
     '9to5Mac', 'https://example.com/source8', true, 'en'),
    ('google-lanza-android-nueva-version',
     'Google lanza la nueva versión de Android con funciones inéditas',
     'La actualización más importante de los últimos años llega con mejoras de seguridad y privacidad',
     'Google ha lanzado la nueva versión de Android con funciones inéditas y mejoras de seguridad.',
     '<p>Google ha lanzado oficialmente la nueva versión de Android, considerada la actualización más importante de los últimos años.</p><h2>Funciones inéditas</h2><p>La nueva versión incluye funciones inéditas como el modo de privacidad avanzada, la integración mejorada con asistente de IA y nuevas opciones de personalización.</p><h2>Mejoras de seguridad</h2><p>La seguridad ha sido uno de los focos principales de esta actualización, con nuevas protecciones contra malware y phishing.</p>',
     'La actualización más importante de los últimos años llega con mejoras de seguridad y privacidad.',
     'Google lanza la nueva versión de Android con funciones inéditas. Mejoras de seguridad, privacidad y análisis completo.',
     'https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Smartphone con la nueva versión de Android mostrando la interfaz',
     'android', NULL, ARRAY['Google','Android','Tecnología','Smartphone','Sistema operativo'],
     'Laura Sánchez', '2026-07-04T11:30:00Z', 3, 78930, 234, 1560, false, false, false,
     '9to5Google', 'https://example.com/source9', true, 'en'),
    ('nvidia-supera-mercado-chips-ia',
     'Nvidia supera el mercado de chips de IA con un nuevo récord de ventas',
     'La compañía lidera el sector de los procesadores para inteligencia artificial con cifras récord',
     'Nvidia ha batido todos los récords de ventas en el mercado de chips para inteligencia artificial.',
     '<p>Nvidia ha superado todos los récords de ventas en el mercado de chips para inteligencia artificial, consolidando su posición de liderazgo en el sector.</p><h2>Cifras récord</h2><p>La compañía ha reportado ingresos trimestrales que superan todas las expectativas del mercado, con un crecimiento interanual superior al 200%.</p><h2>El futuro del sector</h2><p>El dominio de Nvidia en el mercado de chips de IA tiene importantes implicaciones para el futuro del sector tecnológico.</p>',
     'La compañía lidera el sector de los procesadores para inteligencia artificial con cifras récord.',
     'Nvidia supera el mercado de chips de IA con récord de ventas. Análisis del crecimiento y el futuro del sector.',
     'https://images.pexels.com/photos/7988079/pexels-photo-7988079.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Procesador de Nvidia para inteligencia artificial',
     'tecnologia', NULL, ARRAY['Nvidia','IA','Chips','Tecnología','Procesadores'],
     'Laura Sánchez', '2026-07-04T08:00:00Z', 3, 95670, 312, 2340, false, false, true,
     'TechCrunch', 'https://example.com/source10', true, 'en'),
    ('formula-1-gran-premio-verano-resultados',
     'Fórmula 1: emocionante Gran Premio de verano con final de infarto',
     'La carrera ha dejado un resultado sorprendente que cambia el panorama del mundial',
     'La Fórmula 1 ha vivido un Gran Premio de verano emocionante con un final de infarto.',
     '<p>La Fórmula 1 ha vivido un Gran Premio de verano emocionante con un final de infarto que ha cambiado el panorama del mundial.</p><h2>Una carrera de infarto</h2><p>La carrera ha sido una de las más emocionantes de la temporada, con adelantamientos, estrategia y drama hasta la última vuelta.</p><h2>El mundial se aprieta</h2><p>El resultado de esta carrera ha cambiado completamente el panorama del mundial, con la lucha por el título más apretada que nunca.</p>',
     'La carrera ha dejado un resultado sorprendente que cambia el panorama del mundial.',
     'Fórmula 1: Gran Premio de verano con final de infarto. Resultados, análisis y clasificación del mundial.',
     'https://images.pexels.com/photos/2526145/pexels-photo-2526145.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Coches de Fórmula 1 compitiendo en el Gran Premio de verano',
     'formula-1', NULL, ARRAY['Fórmula 1','Gran Premio','Motor','Carreras'],
     'Diego Fernández', '2026-07-04T17:00:00Z', 4, 67890, 234, 1230, false, false, false,
     'Motorsport.com', 'https://example.com/source11', true, 'en'),
    ('motogp-carrera-emocionante-resultados',
     'MotoGP: carrera emocionante con final de infarto en el circuito',
     'El piloto español logra una victoria histórica tras una remontada espectacular',
     'MotoGP ha vivido una carrera emocionante con una victoria histórica del piloto español.',
     '<p>MotoGP ha vivido una carrera emocionante con un final de infarto en el que el piloto español ha logrado una victoria histórica tras una remontada espectacular.</p><h2>Remontada espectacular</h2><p>El piloto español ha realizado una remontada espectacular desde la séptima posición para lograr la victoria en un final de infarto.</p><h2>Clasificación del mundial</h2><p>Esta victoria cambia el panorama del mundial de MotoGP, con el piloto español recortando distancias con el líder.</p>',
     'El piloto español logra una victoria histórica tras una remontada espectacular.',
     'MotoGP: carrera emocionante con victoria histórica del piloto español. Resultados, remontada y clasificación del mundial.',
     'https://images.pexels.com/photos/2526145/pexels-photo-2526145.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Motocicletas de MotoGP compitiendo en el circuito',
     'motogp', NULL, ARRAY['MotoGP','Motor','Carreras','Motociclismo'],
     'Diego Fernández', '2026-07-04T15:30:00Z', 3, 54320, 178, 890, false, false, false,
     'Motorsport.com', 'https://example.com/source12', true, 'en'),
    ('tenis-torneo-gran-slam-resultados',
     'Tenis: el español se clasifica para la final del Gran Slam',
     'El tenista español logra una victoria épica y jugará la final del torneo',
     'El tenista español se ha clasificado para la final de un Gran Slam tras una victoria épica.',
     '<p>El tenista español se ha clasificado para la final de un Gran Slam tras una victoria épica en semifinales.</p><h2>Victoria épica</h2><p>El tenista español ha logrado una victoria épica en cinco sets tras más de cuatro horas de partido.</p><h2>La final</h2><p>El tenista español se enfrentará en la final al número uno del mundo, en lo que promete ser un partido histórico.</p>',
     'El tenista español logra una victoria épica y jugará la final del torneo.',
     'Tenis: el español se clasifica para la final del Gran Slam. Victoria épica en cinco sets y análisis del partido.',
     'https://images.pexels.com/photos/143203/pexels-photo-143203.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Tenista español celebrando la victoria en la cancha',
     'tenis', NULL, ARRAY['Tenis','Gran Slam','Tenista español','Final'],
     'Diego Fernández', '2026-07-04T14:00:00Z', 3, 43210, 145, 670, false, false, false,
     'Tennis World', 'https://example.com/source13', true, 'en'),
    ('nba-finals-resultados-jugadores',
     'NBA: resultados de las finales con actuaciones estelares',
     'Los jugadores estrella brillan en las finales de la NBA con actuaciones memorables',
     'Las finales de la NBA están dejando actuaciones estelares de los jugadores más importantes.',
     '<p>Las finales de la NBA están dejando actuaciones estelares de los jugadores más importantes de la liga.</p><h2>Actuaciones estelares</h2><p>Los jugadores estrella están brillando en las finales con actuaciones memorables que están decidiendo los partidos.</p><h2>El serie de la final</h2><p>El serie de la final está igualado y promete ser uno de los más emocionantes de los últimos años.</p>',
     'Los jugadores estrella brillan en las finales de la NBA con actuaciones memorables.',
     'NBA: resultados de las finales con actuaciones estelares. Análisis de los partidos y los jugadores más destacados.',
     'https://images.pexels.com/photos/274516/pexels-photo-274516.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Jugadores de la NBA durante un partido de las finales',
     'nba', NULL, ARRAY['NBA','Baloncesto','Finales','Playoffs'],
     'Pablo Ortega', '2026-07-04T13:30:00Z', 4, 87650, 312, 1890, false, false, true,
     'ESPN', 'https://example.com/source14', true, 'en'),
    ('economia-mercados-financieros-analisis',
     'Economía: los mercados financieros reaccionan a los últimos datos económicos',
     'El Ibex y las principales bolsas europeas registran subidas tras los datos macroeconómicos',
     'Los mercados financieros reaccionan positivamente a los últimos datos económicos publicados.',
     '<p>Los mercados financieros han reaccionado positivamente a los últimos datos económicos publicados, con el Ibex y las principales bolsas europeas registrando subidas.</p><h2>Datos macroeconómicos</h2><p>Los datos macroeconómicos publicados han superado las expectativas de los analistas, lo que ha generado optimismo en los mercados.</p><h2>Perspectivas</h2><p>Los analistas revisan al alza sus previsiones para los próximos meses tras estos datos positivos.</p>',
     'El Ibex y las principales bolsas europeas registran subidas tras los datos macroeconómicos.',
     'Economía: mercados financieros reaccionan a los últimos datos. Análisis del Ibex, bolsas europeas y perspectivas.',
     'https://images.pexels.com/photos/534216/pexels-photo-534216.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Gráfico de mercados financieros con subidas en el Ibex y bolsas europeas',
     'economia', NULL, ARRAY['Economía','Mercados','Ibex','Bolsa','Finanzas'],
     'María García', '2026-07-04T12:30:00Z', 4, 54320, 156, 890, false, false, false,
     'Cinco Días', 'https://example.com/source15', true, 'es'),
    ('negocios-empresa-tecnologica-financiacion',
     'Negocios: una empresa tecnológica española logra una financiación récord',
     'La startup española cierra una ronda de financiación de 100 millones de euros',
     'Una startup tecnológica española ha cerrado una ronda de financiación récord de 100 millones de euros.',
     '<p>Una startup tecnológica española ha cerrado una ronda de financiación récord de 100 millones de euros, lo que la convierte en uno de los unicornios del país.</p><h2>Ronda de financiación</h2><p>La ronda de financiación ha sido liderada por fondos de inversión internacionales, lo que demuestra el atractivo del ecosistema tecnológico español.</p><h2>Planes de expansión</h2><p>La empresa planea utilizar los fondos para expandirse internacionalmente y reforzar su equipo.</p>',
     'La startup española cierra una ronda de financiación de 100 millones de euros.',
     'Negocios: startup tecnológica española logra financiación récord de 100 millones. Análisis de la ronda y planes de expansión.',
     'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Oficina de una startup tecnológica española con el equipo trabajando',
     'negocios', NULL, ARRAY['Negocios','Startup','Financiación','Tecnología','España'],
     'María García', '2026-07-04T11:00:00Z', 3, 34560, 89, 450, false, false, false,
     'Expansión', 'https://example.com/source16', true, 'es'),
    ('salud-descubrimiento-cientifico-importante',
     'Salud: un descubrimiento científico importante abre nuevas esperanzas',
     'Un equipo de investigadores logra un avance que podría cambiar el tratamiento de enfermedades',
     'Un descubrimiento científico importante abre nuevas esperanzas para el tratamiento de enfermedades.',
     '<p>Un equipo de investigadores ha logrado un avance científico que podría cambiar el tratamiento de varias enfermedades, abriendo nuevas esperanzas para millones de pacientes.</p><h2>Avance científico</h2><p>El avance, publicado en una revista científica de prestigio, permite un mejor entendimiento de las enfermedades y abre nuevas vías de tratamiento.</p><h2>Implicaciones médicas</h2><p>Las implicaciones médicas de este descubrimiento son enormes y podrían cambiar la vida de millones de personas.</p>',
     'Un equipo de investigadores logra un avance que podría cambiar el tratamiento de enfermedades.',
     'Salud: descubrimiento científico importante abre nuevas esperanzas. Avance en el tratamiento de enfermedades y análisis.',
     'https://images.pexels.com/photos/8431211/pexels-photo-8431211.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Investigadores en un laboratorio realizando experimentos científicos',
     'salud', NULL, ARRAY['Salud','Ciencia','Investigación','Medicina'],
     'Elena Torres', '2026-07-04T10:30:00Z', 4, 45670, 134, 780, false, false, false,
     'El Mundo', 'https://example.com/source17', true, 'es'),
    ('ciencia-descubrimiento-espacial-importante',
     'Ciencia: un descubrimiento espacial importante cambia nuestra comprensión del universo',
     'El telescopio espacial ha captado imágenes que revelan nuevos datos sobre el cosmos',
     'Un descubrimiento espacial importante cambia nuestra comprensión del universo.',
     '<p>El telescopio espacial ha captado imágenes que revelan nuevos datos sobre el cosmos, cambiando nuestra comprensión del universo.</p><h2>Imágenes reveladoras</h2><p>Las imágenes captadas por el telescopio espacial muestran detalles nunca antes vistos del universo, lo que permite a los científicos avanzar en su comprensión.</p><h2>Implicaciones científicas</h2><p>Este descubrimiento tiene importantes implicaciones científicas que podrían cambiar nuestra comprensión del cosmos.</p>',
     'El telescopio espacial ha captado imágenes que revelan nuevos datos sobre el cosmos.',
     'Ciencia: descubrimiento espacial importante cambia nuestra comprensión del universo. Imágenes del telescopio y análisis.',
     'https://images.pexels.com/photos/73840/pexels-photo-73840.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Imagen del espacio captada por el telescopio espacial mostrando galaxias',
     'ciencia', NULL, ARRAY['Ciencia','Espacio','Telescopio','Universo','Astronomía'],
     'Elena Torres', '2026-07-04T09:30:00Z', 4, 67890, 178, 1230, false, false, true,
     'National Geographic', 'https://example.com/source18', true, 'en'),
    ('streaming-nueva-serie-exito-audiencia',
     'Streaming: una nueva serie se convierte en el éxito de la temporada',
     'La producción original de la plataforma de streaming bate récords de audiencia',
     'Una nueva serie se ha convertido en el éxito de la temporada en una plataforma de streaming.',
     '<p>Una nueva serie se ha convertido en el éxito de la temporada en una plataforma de streaming, batiendo récords de audiencia.</p><h2>Récord de audiencia</h2><p>La serie ha batido récords de audiencia en la plataforma de streaming, convirtiéndose en la producción más vista del año.</p><h2>Segunda temporada</h2><p>El éxito de la serie ha llevado a la plataforma a confirmar una segunda temporada que se estrenará el próximo año.</p>',
     'La producción original de la plataforma de streaming bate récords de audiencia.',
     'Streaming: nueva serie se convierte en el éxito de la temporada. Récord de audiencia y confirmación de segunda temporada.',
     'https://images.pexels.com/photos/2873493/pexels-photo-2873493.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Escena de la nueva serie de éxito en la plataforma de streaming',
     'streaming', NULL, ARRAY['Streaming','Series','TV','Audiencia'],
     'Sofía López', '2026-07-04T08:30:00Z', 3, 78930, 234, 1560, false, false, true,
     'Variety', 'https://example.com/source19', true, 'en'),
    ('peliculas-estreno-cine-taquilla',
     'Películas: el estreno del verano arrasa en la taquilla mundial',
     'La superproducción bate récords de recaudación en su primer fin de semana',
     'El estreno del verano está arrasando en la taquilla mundial batiendo récords de recaudación.',
     '<p>El estreno del verano está arrasando en la taquilla mundial, batiendo récords de recaudación en su primer fin de semana.</p><h2>Récord de taquilla</h2><p>La superproducción ha batido récords de recaudación en su primer fin de semana, convirtiéndose en el estreno más exitoso del año.</p><h2>Críticas positivas</h2><p>La película ha recibido críticas muy positivas por parte de la prensa especializada y del público.</p>',
     'La superproducción bate récords de recaudación en su primer fin de semana.',
     'Películas: estreno del verano arrasa en la taquilla mundial. Récord de recaudación y críticas positivas.',
     'https://images.pexels.com/photos/2873493/pexels-photo-2873493.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Cartel de la película estreno del verano en la taquilla',
     'peliculas', NULL, ARRAY['Cine','Películas','Taquilla','Estreno'],
     'Sofía López', '2026-07-04T07:30:00Z', 3, 56780, 167, 980, false, false, false,
     'Hollywood Reporter', 'https://example.com/source20', true, 'en'),
    ('series-nueva-temporada-estreno',
     'Series: la nueva temporada más esperada llega por fin',
     'La serie más esperada del año estrena su nueva temporada con gran expectación',
     'La serie más esperada del año estrena su nueva temporada con gran expectación.',
     '<p>La serie más esperada del año estrena su nueva temporada con gran expectación por parte de los fans.</p><h2>Gran expectación</h2><p>La nueva temporada de la serie más esperada del año ha llegado con gran expectación por parte de los fans, que llevaban años esperando este momento.</p><h2>Recepción</h2><p>La recepción por parte de la crítica y del público ha sido muy positiva, superando las expectativas.</p>',
     'La serie más esperada del año estrena su nueva temporada con gran expectación.',
     'Series: nueva temporada más esperada llega por fin. Estreno, expectación y recepción de la crítica y público.',
     'https://images.pexels.com/photos/2873493/pexels-photo-2873493.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Imagen promocional de la nueva temporada de la serie',
     'series', NULL, ARRAY['Series','TV','Estreno','Temporada'],
     'Sofía López', '2026-07-04T06:30:00Z', 3, 64530, 198, 1230, false, false, false,
     'Entertainment Weekly', 'https://example.com/source21', true, 'en'),
    ('viajes-destinos-verano-recomendados',
     'Viajes: los destinos de verano más recomendados para este año',
     'Seleccionamos los mejores destinos para tus vacaciones de verano en España y Europa',
     'Seleccionamos los mejores destinos de verano para tus vacaciones en España y Europa.',
     '<p>Seleccionamos los mejores destinos de verano para tus vacaciones en España y Europa, con opciones para todos los gustos y presupuestos.</p><h2>Destinos de playa</h2><p>Para los amantes de la playa, recomendamos algunos de los mejores destinos costeros de España y Europa.</p><h2>Destinos de interior</h2><p>Para quienes prefieren el interior, hay opciones increíbles que combinan cultura, gastronomía y naturaleza.</p>',
     'Seleccionamos los mejores destinos para tus vacaciones de verano en España y Europa.',
     'Viajes: destinos de verano más recomendados. Selección de los mejores destinos de playa e interior en España y Europa.',
     'https://images.pexels.com/photos/3601425/pexels-photo-3601425.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Playa paradisíaca de España como destino de verano recomendado',
     'viajes', NULL, ARRAY['Viajes','Verano','Vacaciones','Turismo','España'],
     'Sofía López', '2026-07-03T18:00:00Z', 5, 34560, 89, 670, false, false, false,
     'Travel', 'https://example.com/source22', true, 'es'),
    ('videojuegos-lanzamiento-mas-esperado',
     'Videojuegos: el lanzamiento más esperado del año bate récords de ventas',
     'El nuevo videojuego ha superado todas las expectativas en su primer fin de semana',
     'El lanzamiento más esperado del año en videojuegos bate récords de ventas.',
     '<p>El lanzamiento más esperado del año en videojuegos ha batido récords de ventas en su primer fin de semana, superando todas las expectativas.</p><h2>Récord de ventas</h2><p>El nuevo videojuego ha superado todas las expectativas de ventas en su primer fin de semana, convirtiéndose en el lanzamiento más exitoso del año.</p><h2>Críticas excelentes</h2><p>El videojuego ha recibido críticas excelentes por parte de la prensa especializada y de los jugadores.</p>',
     'El nuevo videojuego ha superado todas las expectativas en su primer fin de semana.',
     'Videojuegos: lanzamiento más esperado del año bate récords de ventas. Análisis del éxito y críticas.',
     'https://images.pexels.com/photos/4419140/pexels-photo-4419140.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Imagen del videojuego más esperado del año',
     'videojuegos', NULL, ARRAY['Videojuegos','Gaming','Lanzamiento','Ventas'],
     'Laura Sánchez', '2026-07-03T16:00:00Z', 3, 87650, 312, 2340, false, false, true,
     'IGN', 'https://example.com/source23', true, 'en'),
    ('internacional-cumbre-global-importante',
     'Internacional: cumbre global con decisiones importantes para el futuro',
     'Los líderes mundiales acuerdan medidas clave en la cumbre internacional',
     'Una cumbre global ha tomado decisiones importantes para el futuro del planeta.',
     '<p>Una cumbre global ha tomado decisiones importantes para el futuro del planeta, con acuerdos clave entre los líderes mundiales.</p><h2>Acuerdos clave</h2><p>Los líderes mundiales han acordado medidas clave en la cumbre internacional que tendrán un impacto significativo en el futuro.</p><h2>Implicaciones globales</h2><p>Las decisiones tomadas en esta cumbre tendrán implicaciones globales que afectarán a millones de personas.</p>',
     'Los líderes mundiales acuerdan medidas clave en la cumbre internacional.',
     'Internacional: cumbre global con decisiones importantes. Acuerdos clave de los líderes mundiales y análisis.',
     'https://images.pexels.com/photos/51054/pexels-photo-51054.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Cumbre internacional con líderes mundiales reunidos',
     'internacional', NULL, ARRAY['Internacional','Cumbre','Política','Líderes mundiales'],
     'Javier Ruiz', '2026-07-03T14:00:00Z', 4, 56780, 234, 1230, false, false, false,
     'BBC News', 'https://example.com/source24', true, 'en'),
    ('espana-noticias-actualidad-nacional',
     'España: las noticias más importantes de la actualidad nacional',
     'Repasamos los acontecimientos más relevantes de la semana en España',
     'Repaso completo a las noticias más importantes de la actualidad nacional.',
     '<p>Repasamos los acontecimientos más relevantes de la semana en España, con un análisis completo de la actualidad nacional.</p><h2>Actualidad nacional</h2><p>Las noticias más importantes de la semana en España abarcan desde la política hasta la economía y la sociedad.</p><h2>Análisis completo</h2><p>Ofrecemos un análisis completo de la actualidad nacional con expertos en cada materia.</p>',
     'Repasamos los acontecimientos más relevantes de la semana en España.',
     'España: noticias más importantes de la actualidad nacional. Repaso completo y análisis de los acontecimientos.',
     'https://images.pexels.com/photos/138804/pexels-photo-138804.jpeg?auto=compress&cs=tinysrgb&w=1200',
     'Vista de una ciudad española con monumentos emblemáticos',
     'espana', NULL, ARRAY['España','Actualidad','Nacional','Noticias'],
     'Javier Ruiz', '2026-07-03T12:00:00Z', 5, 45670, 156, 890, false, false, false,
     'El País', 'https://example.com/source25', true, 'es')
  ) AS t(
    slug, title, subtitle, summary, content, excerpt, meta_description,
    image, image_alt, category_slug, subcategory_slug, tags,
    author_name, published_at, reading_time, views, comments_count, shares,
    is_breaking, is_featured, is_trending, source_name, source_url,
    ai_rewritten, original_language
  )
)
INSERT INTO articles (
  slug, title, subtitle, summary, content, excerpt, meta_description,
  image, image_alt, category_id, category_slug, subcategory_slug, tags,
  author_id, published_at, reading_time, views, comments_count, shares,
  is_breaking, is_featured, is_trending, source_id, source_url,
  ai_rewritten, original_language, status
)
SELECT
  d.slug, d.title, d.subtitle, d.summary, d.content, d.excerpt, d.meta_description,
  d.image, d.image_alt, c.id, d.category_slug, d.subcategory_slug, d.tags,
  a.id, d.published_at, d.reading_time, d.views, d.comments_count, d.shares,
  d.is_breaking, d.is_featured, d.is_trending, s.id, d.source_url,
  d.ai_rewritten, d.original_language, 'published'
FROM article_data d
LEFT JOIN categories c ON c.slug = d.category_slug
LEFT JOIN authors a ON a.name = d.author_name
LEFT JOIN sources s ON s.name = d.source_name
ON CONFLICT (slug) DO NOTHING;
